class_name BloodfiendCards
## res://scripts/cards/bloodfiend_cards.gd — Blood Fiend card pack (pluggable)
## 嗜血狂魔: Self-damage, Bloodlust stacks, Vulnerable synergy, Exhaust synergy

enum CardType { ATTACK, SKILL, POWER, STATUS }

static func get_cards() -> Dictionary:
	var db: Dictionary = {}

	# =========================================================================
	# ATTACKS (16 cards)
	# =========================================================================
	db["bf_strike"] = {"id": "bf_strike", "name": "Blood Strike", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 6, "block": 0, "description": "Deal 6 damage.", "art": "res://assets/img/card_art/bf_strike.png", "target": "enemy", "version": "new", "actions": [{"type": "damage"}]}
	db["bf_crimson_slash"] = {"id": "bf_crimson_slash", "name": "Crimson Slash", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 12, "block": 0, "description": "Lose 2 HP.\nDeal 12 damage.", "art": "res://assets/img/card_art/bf_crimson_slash.png", "target": "enemy", "version": "new", "actions": [{"type": "self_damage", "value": 2}, {"type": "damage"}]}
	db["bf_frenzy_claw"] = {"id": "bf_frenzy_claw", "name": "Frenzy Claw", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 4, "block": 0, "description": "Deal 4 damage twice.\nApply 1 Bloodlust\nper hit.", "art": "res://assets/img/card_art/bf_frenzy_claw.png", "target": "enemy", "version": "new", "times": 2, "bf_bloodlust_per_hit": 1, "actions": [{"type": "call", "fn": "frenzy_claw"}]}
	db["bf_gore"] = {"id": "bf_gore", "name": "Gore", "cost": 2, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 10, "block": 0, "description": "Deal 10 damage.\nApply 2 Vulnerable.", "art": "res://assets/img/card_art/bf_gore.png", "target": "enemy", "version": "new", "apply_status": {"type": "vulnerable", "stacks": 2}, "actions": [{"type": "damage"}, {"type": "apply_status", "source": "apply_status"}]}
	db["bf_execution"] = {"id": "bf_execution", "name": "Execution", "cost": 2, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 8, "block": 0, "description": "Deal 8 damage.\nDouble the target's\nBloodlust stacks.", "art": "res://assets/img/card_art/bf_execution.png", "target": "enemy", "version": "new", "actions": [{"type": "call", "fn": "execution"}]}
	db["bf_blood_whirl"] = {"id": "bf_blood_whirl", "name": "Blood Whirl", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 6, "block": 0, "description": "Lose 2 HP.\nDeal 6 damage to\nALL enemies.\nApply 1 Bloodlust.", "art": "res://assets/img/card_art/bf_blood_whirl.png", "target": "all_enemies", "version": "new", "actions": [{"type": "call", "fn": "blood_whirl"}]}
	db["bf_savage_strike"] = {"id": "bf_savage_strike", "name": "Savage Strike", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 6, "block": 0, "description": "Deal 6 damage.\n+1 for each HP lost\nthis combat.", "art": "res://assets/img/card_art/bf_savage_strike.png", "target": "enemy", "version": "new", "actions": [{"type": "call", "fn": "savage_strike"}]}
	db["bf_prey_on_weakness"] = {"id": "bf_prey_on_weakness", "name": "Prey on Weakness", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 6, "block": 0, "description": "Deal 6 damage.\nIf Vulnerable, hit\nan extra time.", "art": "res://assets/img/card_art/bf_prey_on_weakness.png", "target": "enemy", "version": "new", "actions": [{"type": "call", "fn": "prey_on_weakness"}]}
	db["bf_exploit"] = {"id": "bf_exploit", "name": "Exploit", "cost": 0, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 3, "block": 0, "description": "Deal 3 damage.\nIf Vulnerable,\ndraw 1 card.", "art": "res://assets/img/card_art/bf_exploit.png", "target": "enemy", "version": "new", "actions": [{"type": "call", "fn": "exploit"}]}
	db["bf_crushing_blow"] = {"id": "bf_crushing_blow", "name": "Crushing Blow", "cost": 2, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 10, "block": 0, "description": "Deal 10 damage.\nRemove all Vulnerable;\n+4 damage per stack.", "art": "res://assets/img/card_art/bf_crushing_blow.png", "target": "enemy", "version": "new", "vuln_bonus": 4, "actions": [{"type": "call", "fn": "crushing_blow"}]}
	db["bf_flesh_rend"] = {"id": "bf_flesh_rend", "name": "Flesh Rend", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Exhaust 1 card.\nDeal its cost x8\ndamage.", "art": "res://assets/img/card_art/bf_flesh_rend.png", "target": "enemy", "version": "new", "cost_mult": 8, "actions": [{"type": "call", "fn": "flesh_rend"}]}
	db["bf_soul_harvest"] = {"id": "bf_soul_harvest", "name": "Soul Harvest", "cost": 2, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 7, "block": 0, "description": "Exhaust all other\ncards in hand.\nDeal 7 damage for\neach card exhausted.", "art": "res://assets/img/card_art/bf_soul_harvest.png", "target": "enemy", "version": "new", "actions": [{"type": "call", "fn": "soul_harvest"}]}
	db["bf_relentless"] = {"id": "bf_relentless", "name": "Relentless", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 6, "block": 0, "description": "Deal 6 damage.\n+1 hit for each card\nexhausted this turn.", "art": "res://assets/img/card_art/bf_relentless.png", "target": "enemy", "version": "new", "actions": [{"type": "call", "fn": "relentless"}]}
	db["bf_vampiric_embrace"] = {"id": "bf_vampiric_embrace", "name": "Vampiric Embrace", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 4, "block": 0, "description": "Deal 4 damage to\nALL enemies.\nHeal for total damage.\nExhaust.", "art": "res://assets/img/card_art/bf_vampiric_embrace.png", "target": "all_enemies", "version": "new", "exhaust": true, "actions": [{"type": "call", "fn": "vampiric_embrace"}]}
	db["bf_leech"] = {"id": "bf_leech", "name": "Leech", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 6, "block": 0, "description": "Deal 6 damage.\nIf damage dealt,\nheal 2 HP.", "art": "res://assets/img/card_art/bf_leech.png", "target": "enemy", "version": "new", "heal_on_hit": 2, "actions": [{"type": "call", "fn": "leech"}]}
	db["bf_blood_feast"] = {"id": "bf_blood_feast", "name": "Blood Feast", "cost": 1, "type": CardType.ATTACK, "character": "bloodfiend", "damage": 7, "block": 0, "description": "Deal 7 damage.\nIf this kills, gain\n3 Max HP.", "art": "res://assets/img/card_art/bf_blood_feast.png", "target": "enemy", "version": "new", "max_hp_gain": 3, "actions": [{"type": "call", "fn": "blood_feast"}]}

	# =========================================================================
	# SKILLS (14 cards + 1 basic defend)
	# =========================================================================
	db["bf_defend"] = {"id": "bf_defend", "name": "Defend", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 5, "description": "Gain 5 Block.", "art": "res://assets/img/card_art/bf_defend.png", "target": "self", "version": "new", "hero_target": "target_hero", "actions": [{"type": "block"}]}
	db["bf_sanguine_shield"] = {"id": "bf_sanguine_shield", "name": "Sanguine Shield", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 11, "description": "Lose 2 HP.\nGain 11 Block.", "art": "res://assets/img/card_art/bf_sanguine_shield.png", "target": "self", "version": "new", "hero_target": "target_hero", "actions": [{"type": "self_damage", "value": 2}, {"type": "block"}]}
	db["bf_blood_offering"] = {"id": "bf_blood_offering", "name": "Blood Offering", "cost": 0, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Lose 5 HP.\nGain 2 Energy.\nDraw 2 cards.\nExhaust.", "art": "res://assets/img/card_art/bf_blood_offering.png", "target": "self", "version": "new", "exhaust": true, "actions": [{"type": "self_damage", "value": 5}, {"type": "gain_energy", "value": 2}, {"type": "draw", "value": 2}]}
	db["bf_predator_instinct"] = {"id": "bf_predator_instinct", "name": "Predator Instinct", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 0, "description": "This turn, gain 3\nBlock per Attack\nplayed. Draw 1 card.", "art": "res://assets/img/card_art/bf_predator_instinct.png", "target": "self", "version": "new", "draw": 1, "power_effect": "predator_instinct", "power_stacks": 3, "actions": [{"type": "draw"}, {"type": "power_effect", "power": "predator_instinct"}]}
	db["bf_bloodbath"] = {"id": "bf_bloodbath", "name": "Bloodbath", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Exhaust 1 card.\nApply 2 Bloodlust\nand 1 Vulnerable.", "art": "res://assets/img/card_art/bf_bloodbath.png", "target": "enemy", "version": "new", "bf_bloodlust_apply": 2, "apply_status": {"type": "vulnerable", "stacks": 1}, "actions": [{"type": "call", "fn": "bloodbath"}]}
	db["bf_blood_pact"] = {"id": "bf_blood_pact", "name": "Blood Pact", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Exhaust 1 card.\nDraw 2 cards.", "art": "res://assets/img/card_art/bf_blood_pact.png", "target": "self", "version": "new", "draw": 2, "actions": [{"type": "call", "fn": "blood_pact"}]}
	db["bf_sacrifice"] = {"id": "bf_sacrifice", "name": "Sacrifice", "cost": 0, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Lose 3 HP.\nGain 2 Energy.", "art": "res://assets/img/card_art/bf_sacrifice.png", "target": "self", "version": "new", "actions": [{"type": "self_damage", "value": 3}, {"type": "gain_energy", "value": 2}]}
	db["bf_bloodrage"] = {"id": "bf_bloodrage", "name": "Bloodrage", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Lose 2 HP.\nApply 1 Vulnerable\nto ALL enemies.\nGain 2 temp Strength.", "art": "res://assets/img/card_art/bf_bloodrage.png", "target": "all_enemies", "version": "new", "flex_stacks": 2, "actions": [{"type": "call", "fn": "bloodrage"}]}
	db["bf_vital_guard"] = {"id": "bf_vital_guard", "name": "Vital Guard", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 6, "description": "Gain 6 Block.\nIf HP below 28%,\ngain 6 more.", "art": "res://assets/img/card_art/bf_vital_guard.png", "target": "self", "version": "new", "hero_target": "target_hero", "bonus_block": 6, "hp_threshold": 0.28, "actions": [{"type": "call", "fn": "vital_guard"}]}
	db["bf_blood_shell"] = {"id": "bf_blood_shell", "name": "Blood Shell", "cost": 2, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 10, "description": "Gain 10 Block.\nThis turn, when hit,\napply 1 Bloodlust\nto attacker.", "art": "res://assets/img/card_art/bf_blood_shell.png", "target": "self", "version": "new", "hero_target": "target_hero", "power_effect": "blood_shell", "power_stacks": 1, "actions": [{"type": "block"}, {"type": "power_effect", "power": "blood_shell"}]}
	db["bf_blood_rush"] = {"id": "bf_blood_rush", "name": "Blood Rush", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Choose an Attack in\nhand. Reduce its cost\nby 1 this combat.\nExhaust.", "art": "res://assets/img/card_art/bf_blood_rush.png", "target": "self", "version": "new", "exhaust": true, "actions": [{"type": "call", "fn": "blood_rush"}]}
	db["bf_bloodhound"] = {"id": "bf_bloodhound", "name": "Bloodhound", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Draw 3 cards.\nDiscard non-Attack\ncards drawn.", "art": "res://assets/img/card_art/bf_bloodhound.png", "target": "self", "version": "new", "bf_draw_count": 3, "actions": [{"type": "call", "fn": "bloodhound"}]}
	db["bf_berserker_resolve"] = {"id": "bf_berserker_resolve", "name": "Berserker Resolve", "cost": 1, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 6, "description": "Gain 6 Block.\nApply 1 Vulnerable.", "art": "res://assets/img/card_art/bf_berserker_resolve.png", "target": "enemy", "version": "new", "apply_status": {"type": "vulnerable", "stacks": 1}, "actions": [{"type": "block"}, {"type": "apply_status", "source": "apply_status"}]}
	db["bf_survival_instinct"] = {"id": "bf_survival_instinct", "name": "Survival Instinct", "cost": 0, "type": CardType.SKILL, "character": "bloodfiend", "damage": 0, "block": 3, "description": "Gain 3 Block.\nIf HP below 25%,\ngain 7 Block instead.", "art": "res://assets/img/card_art/bf_survival_instinct.png", "target": "self", "version": "new", "hero_target": "target_hero", "actions": [{"type": "call", "fn": "survival_instinct"}]}

	# =========================================================================
	# POWERS (11 cards)
	# =========================================================================
	db["bf_blood_frenzy"] = {"id": "bf_blood_frenzy", "name": "Blood Frenzy", "cost": 3, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "At the start of each\nturn, gain 2 Strength\nand lose 2 HP.", "art": "res://assets/img/card_art/bf_blood_frenzy.png", "target": "self", "version": "new", "hero_target": "target_hero", "power_effect": "blood_frenzy", "per_turn": {"strength": 2, "self_damage": 2}, "power_stacks": 2, "actions": [{"type": "power_effect", "power": "blood_frenzy"}]}
	db["bf_bloodlust"] = {"id": "bf_bloodlust", "name": "Bloodlust", "cost": 1, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Whenever you lose HP,\ngain 1 Strength.", "art": "res://assets/img/card_art/bf_bloodlust.png", "target": "self", "version": "new", "hero_target": "target_hero", "power_effect": "bf_bloodlust_power", "power_stacks": 1, "actions": [{"type": "power_effect", "power": "bf_bloodlust_power"}]}
	db["bf_sanguine_aura"] = {"id": "bf_sanguine_aura", "name": "Sanguine Aura", "cost": 2, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Whenever you deal\nAttack damage, apply\n1 Bloodlust to target.", "art": "res://assets/img/card_art/bf_sanguine_aura.png", "target": "self", "version": "new", "power_effect": "sanguine_aura", "power_stacks": 1, "actions": [{"type": "power_effect", "power": "sanguine_aura"}]}
	db["bf_crimson_pact"] = {"id": "bf_crimson_pact", "name": "Crimson Pact", "cost": 1, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Whenever a card is\nExhausted, deal 5\ndamage to a random\nenemy.", "art": "res://assets/img/card_art/bf_crimson_pact.png", "target": "self", "version": "new", "power_effect": "crimson_pact", "power_stacks": 5, "actions": [{"type": "power_effect", "power": "crimson_pact"}]}
	db["bf_predators_mark"] = {"id": "bf_predators_mark", "name": "Predator's Mark", "cost": 2, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Whenever you apply\nVulnerable, gain\n1 Strength.", "art": "res://assets/img/card_art/bf_predators_mark.png", "target": "self", "version": "new", "hero_target": "target_hero", "power_effect": "predators_mark", "power_stacks": 1, "actions": [{"type": "power_effect", "power": "predators_mark"}]}
	db["bf_blood_scent"] = {"id": "bf_blood_scent", "name": "Blood Scent", "cost": 1, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Whenever you apply\nVulnerable, draw\n1 card.", "art": "res://assets/img/card_art/bf_blood_scent.png", "target": "self", "version": "new", "power_effect": "blood_scent", "power_stacks": 1, "actions": [{"type": "power_effect", "power": "blood_scent"}]}
	db["bf_undying_rage"] = {"id": "bf_undying_rage", "name": "Undying Rage", "cost": 2, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Whenever a card is\nExhausted, gain\n1 Strength.", "art": "res://assets/img/card_art/bf_undying_rage.png", "target": "self", "version": "new", "hero_target": "target_hero", "power_effect": "undying_rage", "power_stacks": 1, "actions": [{"type": "power_effect", "power": "undying_rage"}]}
	db["bf_pain_threshold"] = {"id": "bf_pain_threshold", "name": "Pain Threshold", "cost": 1, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Whenever you lose HP,\ndraw 1 card and\ngain 2 Block.", "art": "res://assets/img/card_art/bf_pain_threshold.png", "target": "self", "version": "new", "hero_target": "target_hero", "power_effect": "pain_threshold", "power_stacks": 2, "actions": [{"type": "power_effect", "power": "pain_threshold"}]}
	db["bf_blood_bond"] = {"id": "bf_blood_bond", "name": "Blood Bond", "cost": 2, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "At the start of each\nturn, if HP below 25%,\ngain 1 Energy and\n1 Strength.", "art": "res://assets/img/card_art/bf_blood_bond.png", "target": "self", "version": "new", "hero_target": "target_hero", "power_effect": "blood_bond", "per_turn": {"conditional": true}, "power_stacks": 1, "actions": [{"type": "power_effect", "power": "blood_bond"}]}
	db["bf_hemostasis"] = {"id": "bf_hemostasis", "name": "Hemostasis", "cost": 2, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "Whenever you lose HP,\ngain equal Block.", "art": "res://assets/img/card_art/bf_hemostasis.png", "target": "self", "version": "new", "hero_target": "target_hero", "power_effect": "hemostasis", "power_stacks": 1, "actions": [{"type": "power_effect", "power": "hemostasis"}]}
	db["bf_undying_will"] = {"id": "bf_undying_will", "name": "Undying Will", "cost": 2, "type": CardType.POWER, "character": "bloodfiend", "damage": 0, "block": 0, "description": "If HP drops to 0,\nsurvive with 1 HP.\n(Triggers 2 times)", "art": "res://assets/img/card_art/bf_undying_will.png", "target": "self", "version": "new", "hero_target": "target_hero", "power_effect": "undying_will", "power_stacks": 2, "actions": [{"type": "power_effect", "power": "undying_will"}]}

	return db

static func get_upgrade_overrides() -> Dictionary:
	return {
		# ATTACKS
		"bf_strike": {"damage": 9, "description": "Deal 9 damage."},
		"bf_crimson_slash": {"damage": 16, "description": "Lose 2 HP.\nDeal 16 damage."},
		"bf_frenzy_claw": {"times": 3, "description": "Deal 4 damage 3 times.\nApply 1 Bloodlust\nper hit."},
		"bf_gore": {"damage": 14, "apply_status": {"type": "vulnerable", "stacks": 3}, "description": "Deal 14 damage.\nApply 3 Vulnerable."},
		"bf_execution": {"damage": 12, "description": "Deal 12 damage.\nDouble the target's\nBloodlust stacks."},
		"bf_blood_whirl": {"damage": 10, "description": "Lose 2 HP.\nDeal 10 damage to\nALL enemies.\nApply 1 Bloodlust."},
		"bf_savage_strike": {"damage": 9, "description": "Deal 9 damage.\n+1 for each HP lost\nthis combat."},
		"bf_prey_on_weakness": {"damage": 9, "description": "Deal 9 damage.\nIf Vulnerable, hit\nan extra time."},
		"bf_exploit": {"damage": 5, "description": "Deal 5 damage.\nIf Vulnerable,\ndraw 2 cards.", "bf_exploit_draw": 2},
		"bf_crushing_blow": {"damage": 14, "vuln_bonus": 5, "description": "Deal 14 damage.\nRemove all Vulnerable;\n+5 damage per stack."},
		"bf_flesh_rend": {"cost_mult": 12, "description": "Exhaust 1 card.\nDeal its cost x12\ndamage."},
		"bf_soul_harvest": {"damage": 10, "description": "Exhaust all other\ncards in hand.\nDeal 10 damage for\neach card exhausted."},
		"bf_relentless": {"damage": 9, "description": "Deal 9 damage.\n+1 hit for each card\nexhausted this turn."},
		"bf_vampiric_embrace": {"damage": 6, "description": "Deal 6 damage to\nALL enemies.\nHeal for total damage.\nExhaust."},
		"bf_leech": {"damage": 9, "description": "Deal 9 damage.\nIf damage dealt,\nheal 2 HP."},
		"bf_blood_feast": {"damage": 10, "max_hp_gain": 4, "description": "Deal 10 damage.\nIf this kills, gain\n4 Max HP."},
		# SKILLS
		"bf_defend": {"block": 8, "description": "Gain 8 Block."},
		"bf_sanguine_shield": {"block": 15, "description": "Lose 2 HP.\nGain 15 Block."},
		"bf_blood_offering": {"actions": [{"type": "self_damage", "value": 5}, {"type": "gain_energy", "value": 3}, {"type": "draw", "value": 3}], "description": "Lose 5 HP.\nGain 3 Energy.\nDraw 3 cards.\nExhaust."},
		"bf_predator_instinct": {"cost": 0, "description": "This turn, gain 3\nBlock per Attack\nplayed. Draw 1 card."},
		"bf_bloodbath": {"bf_bloodlust_apply": 3, "apply_status": {"type": "vulnerable", "stacks": 2}, "description": "Exhaust 1 card.\nApply 3 Bloodlust\nand 2 Vulnerable."},
		"bf_blood_pact": {"draw": 3, "description": "Exhaust 1 card.\nDraw 3 cards."},
		"bf_sacrifice": {"actions": [{"type": "self_damage", "value": 3}, {"type": "gain_energy", "value": 3}], "description": "Lose 3 HP.\nGain 3 Energy."},
		"bf_bloodrage": {"flex_stacks": 4, "description": "Lose 2 HP.\nApply 1 Vulnerable\nto ALL enemies.\nGain 4 temp Strength."},
		"bf_vital_guard": {"block": 9, "bonus_block": 9, "description": "Gain 9 Block.\nIf HP below 25%,\ngain 9 more."},
		"bf_blood_shell": {"block": 14, "power_stacks": 2, "description": "Gain 14 Block.\nThis turn, when hit,\napply 2 Bloodlust\nto attacker."},
		"bf_blood_rush": {"cost": 0, "description": "Choose an Attack in\nhand. Reduce its cost\nby 1 this combat.\nExhaust."},
		"bf_bloodhound": {"bf_draw_count": 4, "description": "Draw 4 cards.\nDiscard non-Attack\ncards drawn."},
		"bf_berserker_resolve": {"block": 9, "apply_status": {"type": "vulnerable", "stacks": 2}, "description": "Gain 9 Block.\nApply 2 Vulnerable."},
		"bf_survival_instinct": {"block": 5, "description": "Gain 5 Block.\nIf HP below 25%,\ngain 10 Block instead.", "bf_low_hp_block": 10},
		# POWERS
		"bf_blood_frenzy": {"description": "At the start of each\nturn, gain 3 Strength\nand lose 2 HP.", "power_effect": "blood_frenzy_plus", "per_turn": {"strength": 3, "self_damage": 2}, "power_stacks": 3},
		"bf_bloodlust": {"description": "Whenever you lose HP,\ngain 2 Strength.", "power_effect": "bf_bloodlust_power_plus", "power_stacks": 2},
		"bf_sanguine_aura": {"cost": 1, "description": "Whenever you deal\nAttack damage, apply\n1 Bloodlust to target."},
		"bf_crimson_pact": {"description": "Whenever a card is\nExhausted, deal 8\ndamage to a random\nenemy.", "power_effect": "crimson_pact_plus", "power_stacks": 8},
		"bf_predators_mark": {"description": "Innate.\nWhenever you apply\nVulnerable, gain\n1 Strength.", "innate": true},
		"bf_blood_scent": {"description": "Whenever you apply\nVulnerable, draw\n2 cards.", "power_effect": "blood_scent_plus"},
		"bf_undying_rage": {"cost": 1, "description": "Whenever a card is\nExhausted, gain\n1 Strength."},
		"bf_pain_threshold": {"description": "Whenever you lose HP,\ndraw 1 card and\ngain 4 Block.", "power_effect": "pain_threshold_plus", "power_stacks": 4},
		"bf_blood_bond": {"description": "At the start of each\nturn, if HP below 25%,\ngain 1 Energy and\n2 Strength.", "power_effect": "blood_bond_plus"},
		"bf_hemostasis": {"cost": 1, "description": "Whenever you lose HP,\ngain equal Block."},
		"bf_undying_will": {"description": "If HP drops to 0,\nsurvive with 1 HP.\n(Triggers 3 times)", "power_stacks": 3},
	}
